<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Manager Login Test"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="0.748">
  <properties />
            <testcase name="loginAsBankManager" time="0.748" classname="testcases.BankManagerLoginTest">
                <failure type="java.lang.AssertionError"
                  message="test the listeners"
              >
<![CDATA[java.lang.AssertionError: test the listeners
  org.testng.Assert.fail(Assert.java:111)
  testcases.BankManagerLoginTest.loginAsBankManager(BankManagerLoginTest.java:18)
  java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
  java.base/java.lang.reflect.Method.invoke(Method.java:580)
  org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
  org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
  org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
  java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
  org.testng.TestRunner.privateRun(TestRunner.java:819)
  org.testng.TestRunner.run(TestRunner.java:619)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
  org.testng.SuiteRunner.run(SuiteRunner.java:336)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
  org.testng.TestNG.runSuites(TestNG.java:1134)
  org.testng.TestNG.run(TestNG.java:1101)
  org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
  org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
  org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
  org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
  org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
  org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
  org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
